<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40" started-at="2018-07-03T06:39:49Z" finished-at="2018-07-03T06:39:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="40" started-at="2018-07-03T06:39:49Z" finished-at="2018-07-03T06:39:49Z">
      <class name="com.experitest.auto.AndroidDemoTest">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:com.experitest.auto.AndroidDemoTest@f6c48ac]" name="setUp" is-config="true" duration-ms="0" started-at="2018-07-03T10:39:49Z" finished-at="2018-07-03T10:39:49Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.experitest.auto.AndroidDemoTest.setUp(AndroidDemoTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:585)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="testUntitled()[pri:0, instance:com.experitest.auto.AndroidDemoTest@f6c48ac]" name="testUntitled" duration-ms="2" started-at="2018-07-03T10:39:49Z" finished-at="2018-07-03T10:39:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUntitled -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:com.experitest.auto.AndroidDemoTest@f6c48ac]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-07-03T10:39:49Z" finished-at="2018-07-03T10:39:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.experitest.auto.AndroidDemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
